server:
  port: 8080

spring:
  application:
    name: PRODUCT-SERVICE
  config:
    import: configserver:http://localhost:9296
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/product_db
    username: root
    password: phak1502
  jpa:
    hibernate:
      ddl-auto: update

#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}
